version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
    environment:
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_BLACKANDWHITE=${S3_BUCKET_BLACKANDWHITE}
      - AWS_REGION=${AWS_REGION}
    command: forever server.js
    restart: always
